// Content data definitions for all expansion clusters
// This file defines every new page to be generated

export const TODAY = '2026-02-19';

// ============================================================
// CLUSTER 1: Cost/Pricing Hub (25 pages)
// ============================================================
export const costPages = [
  { slug: 'how-much-does-a-vet-visit-cost', title: 'How Much Does a Vet Visit Cost', desc: 'Average vet visit costs for dogs and cats, what affects pricing, and how to save on veterinary bills. Covers routine checkups, sick visits, and specialist consultations.', animal: 'general', affiliateCategories: ['insuranceAndWellness', 'teleVetsAndClinics', 'pharmacyAndMedical'] },
  { slug: 'dog-surgery-costs', title: 'Dog Surgery Costs', desc: 'Common dog surgery costs from spay/neuter to emergency procedures. Covers ACL repair, tumor removal, dental surgery, and how pet insurance helps.', animal: 'dogs', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'teleVetsAndClinics'] },
  { slug: 'cat-surgery-costs', title: 'Cat Surgery Costs', desc: 'Average costs for common cat surgeries including spay/neuter, dental extractions, tumor removal, and urinary obstruction surgery with insurance tips.', animal: 'cats', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'teleVetsAndClinics'] },
  { slug: 'pet-cremation-cost', title: 'Pet Cremation and End-of-Life Costs', desc: 'Complete guide to pet cremation costs, burial options, euthanasia fees, and memorial services. Covers private vs communal cremation and at-home options.', animal: 'general', affiliateCategories: ['insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'pet-insurance-cost-by-breed', title: 'Pet Insurance Cost by Breed', desc: 'How much pet insurance costs for every major dog and cat breed. Factors affecting premiums, cheapest and most expensive breeds to insure, and best value plans.', animal: 'general', affiliateCategories: ['insuranceAndWellness'] },
  { slug: 'dog-grooming-costs', title: 'How Much Does Dog Grooming Cost', desc: 'Average dog grooming prices by breed size and service type. Covers bathing, haircuts, nail trimming, teeth cleaning, and mobile grooming fees.', animal: 'dogs', affiliateCategories: ['groomingAndSupplements', 'foodAndNutrition'] },
  { slug: 'pet-dental-cleaning-cost', title: 'Pet Dental Cleaning Cost', desc: 'Average costs for professional dog and cat dental cleanings, tooth extractions, and dental X-rays. Includes tips to reduce dental care expenses.', animal: 'general', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'dog-training-costs', title: 'How Much Does Dog Training Cost', desc: 'Dog training costs for group classes, private sessions, board-and-train, and online programs. Covers puppy training, obedience, and behavioral modification pricing.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior'] },
  { slug: 'pet-boarding-costs', title: 'Pet Boarding and Sitting Costs', desc: 'Average pet boarding, pet sitting, and doggy daycare costs by location and service type. Includes tips for finding affordable care while traveling.', animal: 'general', affiliateCategories: ['walkingSittingBoarding'] },
  { slug: 'how-much-does-a-puppy-cost', title: 'How Much Does a Puppy Cost First Year', desc: 'Total first-year puppy costs including purchase price, vaccinations, food, supplies, training, and unexpected expenses. Budget planning guide for new dog owners.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'insuranceAndWellness', 'trainingAndBehavior', 'groomingAndSupplements'] },
  { slug: 'how-much-does-a-kitten-cost', title: 'How Much Does a Kitten Cost First Year', desc: 'Complete first-year kitten cost breakdown covering adoption fees, vaccinations, spay/neuter, food, litter, supplies, and veterinary care.', animal: 'cats', affiliateCategories: ['foodAndNutrition', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'emergency-vet-costs', title: 'Emergency Vet Visit Costs', desc: 'How much emergency vet visits cost for dogs and cats. Covers after-hours fees, common emergencies, and how to prepare financially for pet emergencies.', animal: 'general', affiliateCategories: ['insuranceAndWellness', 'teleVetsAndClinics', 'pharmacyAndMedical'] },
  { slug: 'dog-vaccination-costs', title: 'Dog Vaccination Costs and Schedules', desc: 'Complete dog vaccination cost guide covering core vaccines, optional vaccines, puppy vaccination schedules, and booster shot pricing.', animal: 'dogs', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'teleVetsAndClinics'] },
  { slug: 'cat-vaccination-costs', title: 'Cat Vaccination Costs and Schedules', desc: 'Cat vaccination costs for FVRCP, rabies, FeLV, and optional vaccines. Includes kitten vaccination schedules and where to find affordable shots.', animal: 'cats', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'pet-microchipping-cost', title: 'Pet Microchipping Cost and Guide', desc: 'How much pet microchipping costs, how it works, where to get it done, and why every pet should be microchipped. Covers registration and updating information.', animal: 'general', affiliateCategories: ['insuranceAndWellness', 'devicesGpsAndTech'] },
  { slug: 'heartworm-treatment-cost', title: 'Heartworm Treatment Cost for Dogs', desc: 'Complete guide to heartworm treatment costs, the treatment process, prevention costs, and how insurance covers heartworm disease in dogs.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'flea-tick-prevention-cost', title: 'Flea and Tick Prevention Costs', desc: 'Monthly and annual costs of flea and tick prevention for dogs and cats. Compares topical, oral, and collar options with effectiveness ratings.', animal: 'general', affiliateCategories: ['pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'dog-allergy-testing-cost', title: 'Dog Allergy Testing Cost', desc: 'Costs of dog allergy testing including blood tests, skin tests, and elimination diets. Covers food allergy testing, environmental allergy panels, and treatment costs.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'pet-x-ray-cost', title: 'Pet X-Ray and Imaging Costs', desc: 'Average costs for pet X-rays, ultrasounds, MRIs, and CT scans. Covers when imaging is needed and how pet insurance helps with diagnostic costs.', animal: 'general', affiliateCategories: ['insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'spay-neuter-cost', title: 'Spay and Neuter Cost Guide', desc: 'Average spay and neuter costs for dogs and cats by size and location. Covers low-cost options, what the surgery includes, and recovery expectations.', animal: 'general', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'bird-vet-costs', title: 'Bird Veterinary Care Costs', desc: 'Avian vet visit costs, common bird health procedures, and annual care budgets for parrots, cockatiels, and other pet birds.', animal: 'birds', affiliateCategories: ['birdReptileExotic', 'insuranceAndWellness'] },
  { slug: 'reptile-vet-costs', title: 'Reptile Veterinary Care Costs', desc: 'Exotic vet costs for reptiles including checkups, surgery, and diagnostics. Budget planning for bearded dragons, ball pythons, and other reptile pets.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic', 'insuranceAndWellness'] },
  { slug: 'fish-aquarium-setup-costs', title: 'Aquarium Setup and Maintenance Costs', desc: 'Complete aquarium cost breakdown covering tank, equipment, fish, plants, and ongoing maintenance for freshwater and saltwater setups.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'pet-medication-costs', title: 'Common Pet Medication Costs', desc: 'Average costs for common pet medications including antibiotics, pain meds, anti-inflammatories, and chronic condition drugs. Tips for saving on prescriptions.', animal: 'general', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'lifetime-cost-of-owning-a-dog', title: 'Lifetime Cost of Owning a Dog', desc: 'Total lifetime dog ownership costs from puppy to senior years. Covers annual expenses, unexpected costs, and how to budget for 10-15 years of dog ownership.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'insuranceAndWellness', 'groomingAndSupplements', 'pharmacyAndMedical'] },
];

// ============================================================
// CLUSTER 2: Safety/Toxicity Hub (28 pages)
// ============================================================
export const safetyPages = [
  { slug: 'can-dogs-eat-grapes', title: 'Can Dogs Eat Grapes and Raisins', desc: 'Why grapes and raisins are toxic to dogs, symptoms of grape poisoning, what to do if your dog eats grapes, and emergency treatment guide.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'can-dogs-eat-chocolate', title: 'Can Dogs Eat Chocolate', desc: 'Complete guide to chocolate toxicity in dogs. Covers which types are most dangerous, toxic doses by weight, symptoms, and emergency treatment.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'can-dogs-eat-onions', title: 'Can Dogs Eat Onions and Garlic', desc: 'Why onions, garlic, leeks, and chives are toxic to dogs. Covers symptoms of allium poisoning, dangerous amounts, and treatment.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'can-dogs-eat-xylitol', title: 'Xylitol Poisoning in Dogs', desc: 'Why xylitol (birch sugar) is deadly for dogs. Products containing xylitol, symptoms, emergency treatment, and prevention guide.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'can-dogs-eat-avocado', title: 'Can Dogs Eat Avocado', desc: 'Is avocado safe for dogs? Covers persin toxicity, pit hazards, which parts are dangerous, and what to do if your dog eats avocado.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'foodAndNutrition'] },
  { slug: 'can-dogs-eat-nuts', title: 'Which Nuts Are Safe for Dogs', desc: 'Complete guide to nuts and dogs. Covers macadamia toxicity, safe nuts, choking hazards, and portion guidelines for dogs.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'foodAndNutrition'] },
  { slug: 'can-dogs-eat-bones', title: 'Can Dogs Eat Bones Safely', desc: 'Which bones are safe for dogs and which are dangerous. Covers cooked vs raw, splintering risks, safe alternatives, and choking prevention.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'teleVetsAndClinics'] },
  { slug: 'foods-toxic-to-cats', title: 'Foods Toxic to Cats', desc: 'Complete list of foods dangerous or toxic to cats including lilies, onions, chocolate, alcohol, caffeine, and raw dough with emergency guidance.', animal: 'cats', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'plants-toxic-to-dogs', title: 'Plants Toxic to Dogs', desc: 'Common household and garden plants toxic to dogs. Covers lilies, sago palm, azaleas, oleander, tulips, and 40+ dangerous plants with symptoms.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'plants-toxic-to-cats', title: 'Plants Toxic to Cats', desc: 'Household and outdoor plants dangerous to cats. Covers lilies (extremely toxic), poinsettias, aloe vera, and safe plant alternatives for cat owners.', animal: 'cats', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'essential-oils-toxic-to-dogs', title: 'Essential Oils Toxic to Dogs', desc: 'Which essential oils are dangerous for dogs and which are safe. Covers diffusers, topical exposure, ingestion risks, and pet-safe alternatives.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'anxietyAndCalming'] },
  { slug: 'essential-oils-toxic-to-cats', title: 'Essential Oils Toxic to Cats', desc: 'Why most essential oils are dangerous for cats. Covers which oils to avoid, diffuser safety, symptoms of toxicity, and cat-safe alternatives.', animal: 'cats', affiliateCategories: ['teleVetsAndClinics', 'anxietyAndCalming'] },
  { slug: 'human-medications-toxic-to-pets', title: 'Human Medications Toxic to Pets', desc: 'Common human medications dangerous to dogs and cats including ibuprofen, acetaminophen, antidepressants, and ADHD drugs. Emergency response guide.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'household-chemicals-toxic-to-pets', title: 'Household Chemicals Toxic to Pets', desc: 'Cleaning products, pesticides, antifreeze, and other household chemicals dangerous to pets. Covers safe alternatives and poison-proofing your home.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'can-dogs-eat-peanut-butter', title: 'Can Dogs Eat Peanut Butter', desc: 'Is peanut butter safe for dogs? Covers xylitol dangers, safe brands, portion sizes, and how to use peanut butter for training and enrichment.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'trainingAndBehavior'] },
  { slug: 'can-dogs-eat-cheese', title: 'Can Dogs Eat Cheese and Dairy', desc: 'Which cheeses are safe for dogs, lactose intolerance signs, safe dairy products, and how much cheese dogs can eat without problems.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'teleVetsAndClinics'] },
  { slug: 'can-dogs-eat-eggs', title: 'Can Dogs Eat Eggs', desc: 'Are eggs safe for dogs? Covers raw vs cooked, nutritional benefits, biotin concerns, and how to safely prepare eggs for your dog.', animal: 'dogs', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'can-cats-eat-tuna', title: 'Can Cats Eat Tuna', desc: 'Is tuna safe for cats? Covers mercury risks, nutritional concerns, how much tuna is safe, and better fish alternatives for cats.', animal: 'cats', affiliateCategories: ['foodAndNutrition', 'teleVetsAndClinics'] },
  { slug: 'safe-fruits-for-dogs', title: 'Safe Fruits and Vegetables for Dogs', desc: 'Complete list of fruits and vegetables safe for dogs, portion sizes, preparation tips, and which produce to avoid.', animal: 'dogs', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'safe-foods-for-cats', title: 'Safe Human Foods for Cats', desc: 'Which human foods cats can safely eat, proper portions, foods to always avoid, and healthy treat alternatives for cats.', animal: 'cats', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'antifreeze-poisoning-pets', title: 'Antifreeze Poisoning in Pets', desc: 'Why antifreeze is one of the deadliest pet poisons. Covers ethylene glycol toxicity, symptoms, emergency treatment, and prevention tips.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'rat-poison-dogs', title: 'Rat Poison and Rodenticide Toxicity in Dogs', desc: 'Types of rat poison and their effects on dogs. Covers symptoms by poison type, emergency treatment, and pet-safe rodent control alternatives.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'dog-mushroom-poisoning', title: 'Mushroom Poisoning in Dogs', desc: 'Toxic mushroom species dangerous to dogs, symptoms of mushroom poisoning, emergency response, and preventing mushroom ingestion on walks.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'marijuana-toxicity-pets', title: 'Marijuana and THC Toxicity in Pets', desc: 'Effects of marijuana, THC edibles, and CBD products on dogs and cats. Covers symptoms, emergency treatment, and keeping cannabis products away from pets.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'fertilizer-pesticide-pet-safety', title: 'Lawn Chemical and Fertilizer Safety for Pets', desc: 'How lawn fertilizers, herbicides, and pesticides affect pets. Covers safe products, waiting times after application, and organic alternatives.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'foods-safe-for-birds', title: 'Safe and Toxic Foods for Pet Birds', desc: 'Complete guide to safe fruits, vegetables, seeds, and grains for pet birds plus foods that are toxic including avocado, chocolate, and caffeine.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'reptile-food-safety', title: 'Safe and Dangerous Foods for Reptiles', desc: 'Feeding safety guide for bearded dragons, leopard geckos, and other pet reptiles. Covers toxic insects, unsafe vegetables, and calcium requirements.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'pet-proofing-your-home', title: 'Pet-Proofing Your Home Room by Room', desc: 'Complete home safety guide for pet owners covering every room. Eliminates hazards from kitchen chemicals to bathroom medications to garage antifreeze.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'devicesGpsAndTech', 'insuranceAndWellness'] },
];

// ============================================================
// CLUSTER 3: Emergency Response Hub (18 pages)
// ============================================================
export const emergencyPages = [
  { slug: 'dog-choking-emergency', title: 'Dog Choking Emergency Guide', desc: 'Step-by-step guide for helping a choking dog. Covers Heimlich maneuver for dogs, recognizing choking vs coughing, and when to rush to the vet.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'dog-heatstroke-emergency', title: 'Dog Heatstroke Emergency Guide', desc: 'How to recognize and treat heatstroke in dogs. Covers cooling techniques, high-risk breeds, prevention, and when heatstroke becomes life-threatening.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'devicesGpsAndTech'] },
  { slug: 'dog-seizure-emergency', title: 'Dog Seizure Emergency Guide', desc: 'What to do when your dog has a seizure. Covers types of seizures, how to keep your dog safe, epilepsy management, and when seizures are emergencies.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'dog-bloat-emergency', title: 'Dog Bloat (GDV) Emergency Guide', desc: 'Recognizing and responding to bloat in dogs. Covers symptoms of GDV, at-risk breeds, why bloat is life-threatening, and prevention strategies.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'dog-poisoning-emergency', title: 'Dog Poisoning Emergency Response', desc: 'What to do if your dog eats something toxic. Covers when to induce vomiting, when not to, poison control numbers, and emergency vet protocols.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'cat-urinary-blockage-emergency', title: 'Cat Urinary Blockage Emergency', desc: 'Recognizing urinary blockage in cats — a life-threatening emergency. Covers symptoms, why male cats are at higher risk, treatment, and prevention.', animal: 'cats', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'pet-bleeding-emergency', title: 'Pet Bleeding Emergency First Aid', desc: 'How to stop bleeding in dogs and cats from cuts, nail injuries, and trauma. Covers pressure techniques, tourniquet basics, and when to seek emergency care.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'pet-broken-bone-emergency', title: 'Pet Broken Bone Emergency Guide', desc: 'How to handle a suspected broken bone in your dog or cat. Covers immobilization, pain management, transport to the vet, and fracture treatment costs.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'dog-bite-emergency', title: 'Dog Bite Emergency and Wound Care', desc: 'Emergency treatment for dog bite wounds on pets and humans. Covers cleaning wounds, infection prevention, when stitches are needed, and legal considerations.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'pet-drowning-emergency', title: 'Pet Drowning and Water Safety', desc: 'Emergency response for pet drowning, CPR for dogs and cats, pool safety, and water hazards every pet owner should know about.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'pet-burn-emergency', title: 'Pet Burn Emergency Treatment', desc: 'How to treat burns in pets from hot surfaces, chemicals, and electrical sources. Covers first aid, severity assessment, and veterinary treatment.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'dog-allergic-reaction-emergency', title: 'Dog Allergic Reaction and Anaphylaxis', desc: 'Recognizing allergic reactions in dogs including bee stings, vaccine reactions, and anaphylaxis. Covers Benadryl dosing, EpiPen use, and emergency response.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'pet-eye-injury-emergency', title: 'Pet Eye Injury Emergency Guide', desc: 'How to handle eye injuries in dogs and cats including scratches, foreign objects, chemical exposure, and when eye injuries require emergency surgery.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'dog-snake-bite-emergency', title: 'Dog Snake Bite Emergency Guide', desc: 'What to do if your dog is bitten by a snake. Covers venomous vs non-venomous bites, first aid, treatment costs, and regional snake identification.', animal: 'dogs', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'cat-fall-injury', title: 'Cat Fall Injury Guide (High-Rise Syndrome)', desc: 'What to do when a cat falls from a height. Covers high-rise syndrome, internal injury signs, emergency transport, and window safety for cats.', animal: 'cats', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'pet-cpr-guide', title: 'Pet CPR and Rescue Breathing Guide', desc: 'Step-by-step CPR instructions for dogs and cats. Covers chest compressions, rescue breathing, when to perform CPR, and CPR certification for pet owners.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'when-to-go-to-emergency-vet', title: 'When to Go to the Emergency Vet', desc: 'Clear guide on symptoms and situations that require an emergency vet visit vs those that can wait. Covers dogs, cats, and exotic pets.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'pet-emergency-kit', title: 'Pet Emergency Kit Checklist', desc: 'Essential items for a pet first aid and emergency kit. Covers supplies, medications, documents, and disaster preparedness for all pet types.', animal: 'general', affiliateCategories: ['teleVetsAndClinics', 'insuranceAndWellness', 'pharmacyAndMedical'] },
];

// ============================================================
// CLUSTER 4: Disease Expansion — Dogs (22 pages)
// ============================================================
export const dogDiseasePages = [
  { slug: 'dog-uti-urinary-tract-infection', title: 'Dog Urinary Tract Infections (UTIs)', desc: 'Complete guide to UTIs in dogs covering symptoms, causes, diagnosis, treatment options, prevention, and when UTIs indicate a more serious condition.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'dog-pancreatitis', title: 'Pancreatitis in Dogs', desc: 'Causes, symptoms, and treatment of pancreatitis in dogs. Covers acute vs chronic pancreatitis, dietary management, and long-term care strategies.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'dog-cushings-disease', title: "Cushing's Disease in Dogs", desc: "Complete guide to Cushing's disease (hyperadrenocorticism) in dogs. Covers symptoms, diagnosis, treatment options, and managing quality of life.", animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'dog-hypothyroidism', title: 'Hypothyroidism in Dogs', desc: 'Understanding hypothyroidism in dogs including symptoms, blood test diagnosis, thyroid medication, and long-term management of this common condition.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'dog-ivdd-disc-disease', title: 'IVDD (Intervertebral Disc Disease) in Dogs', desc: 'Complete guide to IVDD in dogs. Covers symptoms, at-risk breeds (Dachshunds, Corgis), treatment options from conservative to surgery, and recovery.', animal: 'dogs', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'teleVetsAndClinics'] },
  { slug: 'dog-diabetes', title: 'Diabetes in Dogs', desc: 'Managing diabetes in dogs including symptoms, insulin therapy, blood glucose monitoring, dietary management, and daily care routines.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'dog-heart-disease', title: 'Heart Disease in Dogs', desc: 'Types of heart disease in dogs including DCM, valve disease, and congestive heart failure. Covers symptoms, diagnosis, medications, and prognosis.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'dog-colitis-ibd', title: 'Colitis and IBD in Dogs', desc: 'Guide to inflammatory bowel disease and colitis in dogs. Covers chronic diarrhea, diagnostic workup, dietary trials, medications, and management.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'foodAndNutrition', 'insuranceAndWellness'] },
  { slug: 'dog-ear-infections', title: 'Dog Ear Infections Guide', desc: 'Complete guide to ear infections in dogs. Covers outer, middle, and inner ear infections, treatment, prevention, and breeds prone to ear problems.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'groomingAndSupplements'] },
  { slug: 'dog-skin-allergies', title: 'Dog Skin Allergies and Dermatitis', desc: 'Types of skin allergies in dogs including atopic dermatitis, food allergies, and contact allergies. Covers symptoms, testing, treatments, and itch relief.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'groomingAndSupplements', 'foodAndNutrition'] },
  { slug: 'dog-anxiety-disorders', title: 'Anxiety Disorders in Dogs', desc: 'Understanding dog anxiety including separation anxiety, noise phobia, and generalized anxiety. Covers behavioral therapy, medications, and calming aids.', animal: 'dogs', affiliateCategories: ['anxietyAndCalming', 'trainingAndBehavior', 'pharmacyAndMedical'] },
  { slug: 'dog-obesity', title: 'Dog Obesity Prevention and Weight Loss', desc: 'Addressing obesity in dogs including health risks, ideal weight assessment, diet plans, exercise programs, and monitoring progress safely.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'insuranceAndWellness', 'groomingAndSupplements'] },
  { slug: 'dog-dental-disease', title: 'Dental Disease in Dogs', desc: 'Periodontal disease in dogs covering stages, symptoms, professional cleaning, home dental care, and preventing tooth loss and infections.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'groomingAndSupplements', 'insuranceAndWellness'] },
  { slug: 'dog-parvovirus', title: 'Parvovirus in Dogs and Puppies', desc: 'Complete guide to canine parvovirus. Covers symptoms, treatment, survival rates, vaccination importance, and disinfection protocols.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'dog-kennel-cough', title: 'Kennel Cough in Dogs', desc: 'Understanding kennel cough (infectious tracheobronchitis) in dogs. Covers symptoms, treatment, Bordetella vaccination, and when it becomes pneumonia.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'dog-lyme-disease', title: 'Lyme Disease in Dogs', desc: 'Lyme disease in dogs from tick bites. Covers symptoms, testing, antibiotic treatment, vaccination, and tick prevention strategies.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'dog-hotspots', title: 'Hot Spots on Dogs', desc: 'Causes and treatment of hot spots (acute moist dermatitis) in dogs. Covers home treatment, when to see the vet, and preventing recurrence.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'dog-cataracts', title: 'Cataracts in Dogs', desc: 'Understanding cataracts in dogs including causes, stages, surgery options, costs, and managing vision loss in senior dogs.', animal: 'dogs', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'teleVetsAndClinics'] },
  { slug: 'dog-cruciate-ligament-injury', title: 'ACL/Cruciate Ligament Injury in Dogs', desc: 'Guide to cranial cruciate ligament (CCL/ACL) tears in dogs. Covers symptoms, surgical options (TPLO, TTA), recovery timelines, and costs.', animal: 'dogs', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'dog-intestinal-parasites', title: 'Intestinal Parasites in Dogs', desc: 'Common intestinal worms in dogs including roundworms, hookworms, whipworms, and tapeworms. Covers symptoms, deworming, and prevention protocols.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'dog-mange', title: 'Mange in Dogs (Demodectic and Sarcoptic)', desc: 'Complete guide to mange in dogs. Covers demodectic vs sarcoptic mange, symptoms, treatment options, and recovery expectations.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'groomingAndSupplements', 'insuranceAndWellness'] },
  { slug: 'dog-addisons-disease', title: "Addison's Disease in Dogs", desc: "Understanding Addison's disease (hypoadrenocorticism) in dogs. Covers symptoms, crisis situations, lifelong treatment, and daily management.", animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
];

// ============================================================
// CLUSTER 5: Disease Expansion — Cats (18 pages)
// ============================================================
export const catDiseasePages = [
  { slug: 'cat-feline-leukemia-felv', title: 'Feline Leukemia Virus (FeLV)', desc: 'Complete guide to FeLV in cats covering transmission, testing, symptoms, treatment options, prevention, and managing FeLV-positive cats.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'cat-fiv', title: 'Feline Immunodeficiency Virus (FIV)', desc: 'Understanding FIV in cats. Covers transmission, testing, stages, treatment, living with an FIV-positive cat, and multi-cat household management.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'cat-pancreatitis', title: 'Pancreatitis in Cats', desc: 'Causes, symptoms, and treatment of feline pancreatitis. Covers diagnosis challenges, dietary management, and connection to triaditis.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'cat-asthma', title: 'Feline Asthma', desc: 'Complete guide to asthma in cats covering triggers, symptoms, inhaler use, medications, and environmental management to reduce attacks.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'cat-ibd', title: 'Inflammatory Bowel Disease (IBD) in Cats', desc: 'Understanding IBD in cats. Covers chronic vomiting and diarrhea, diagnosis, dietary trials, medication options, and long-term management.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'foodAndNutrition', 'insuranceAndWellness'] },
  { slug: 'cat-obesity', title: 'Cat Obesity Prevention and Weight Loss', desc: 'Managing overweight cats including health risks, ideal weight ranges, feeding strategies, portion control, and exercise ideas for indoor cats.', animal: 'cats', affiliateCategories: ['foodAndNutrition', 'insuranceAndWellness'] },
  { slug: 'cat-diabetes', title: 'Diabetes in Cats', desc: 'Managing feline diabetes including symptoms, insulin therapy, blood glucose monitoring, dietary management, and potential for diabetic remission.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'cat-heart-disease', title: 'Heart Disease in Cats (HCM)', desc: 'Hypertrophic cardiomyopathy and other heart conditions in cats. Covers symptoms, diagnosis, treatment, at-risk breeds, and prognosis.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'cat-cancer-signs', title: 'Cancer Signs in Cats', desc: 'How to recognize cancer symptoms in cats. Covers common types (lymphoma, squamous cell carcinoma), warning signs, diagnosis, and treatment options.', animal: 'cats', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'teleVetsAndClinics'] },
  { slug: 'cat-upper-respiratory-infection', title: 'Cat Upper Respiratory Infections', desc: 'Guide to URI in cats covering herpesvirus, calicivirus, symptoms, home care, when antibiotics are needed, and preventing spread in multi-cat homes.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'cat-dental-disease-guide', title: 'Dental Disease in Cats', desc: 'Feline dental disease including stomatitis, tooth resorption, and periodontal disease. Covers symptoms, dental procedures, and home dental care.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'groomingAndSupplements'] },
  { slug: 'cat-constipation', title: 'Cat Constipation and Megacolon', desc: 'Understanding constipation in cats from mild to severe megacolon. Covers causes, home remedies, laxatives, dietary changes, and when surgery is needed.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'foodAndNutrition', 'insuranceAndWellness'] },
  { slug: 'cat-skin-allergies', title: 'Cat Skin Allergies and Dermatitis', desc: 'Types of skin allergies in cats including food allergies, flea allergy dermatitis, and environmental allergies. Covers testing, treatment, and itch relief.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'groomingAndSupplements', 'foodAndNutrition'] },
  { slug: 'cat-intestinal-parasites', title: 'Intestinal Parasites in Cats', desc: 'Common worms in cats including roundworms, tapeworms, hookworms, and coccidia. Covers symptoms, deworming protocols, and indoor cat prevention.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness'] },
  { slug: 'cat-ear-infections', title: 'Cat Ear Infections Guide', desc: 'Ear infections in cats covering bacterial, yeast, and ear mite infections. Covers symptoms, treatment, cleaning techniques, and prevention.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'cat-fip', title: 'Feline Infectious Peritonitis (FIP)', desc: 'Understanding FIP in cats including wet and dry forms, diagnosis, the GS-441524 treatment breakthrough, and prognosis for affected cats.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'insuranceAndWellness', 'teleVetsAndClinics'] },
  { slug: 'cat-litter-box-problems', title: 'Cat Litter Box Problems and Solutions', desc: 'Why cats stop using the litter box. Covers medical causes, behavioral causes, box setup optimization, cleaning protocols, and multi-cat strategies.', animal: 'cats', affiliateCategories: ['anxietyAndCalming', 'pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'cat-overgrooming', title: 'Cat Overgrooming (Psychogenic Alopecia)', desc: 'Understanding excessive grooming and hair loss in cats. Covers stress triggers, medical vs behavioral causes, treatment options, and environmental enrichment.', animal: 'cats', affiliateCategories: ['anxietyAndCalming', 'pharmacyAndMedical', 'groomingAndSupplements'] },
];

// ============================================================
// CLUSTER 6: Behavioral/Training (22 pages)
// ============================================================
export const behaviorPages = [
  { slug: 'dog-separation-anxiety', title: 'Dog Separation Anxiety', desc: 'Complete guide to separation anxiety in dogs. Covers symptoms, desensitization training, medications, calming aids, and preventing anxiety in puppies.', animal: 'dogs', affiliateCategories: ['anxietyAndCalming', 'trainingAndBehavior', 'pharmacyAndMedical'] },
  { slug: 'dog-noise-phobia', title: 'Dog Noise Phobia (Thunder, Fireworks)', desc: 'Managing noise phobia in dogs including thunderstorm anxiety and fireworks fear. Covers desensitization, calming products, medications, and safe spaces.', animal: 'dogs', affiliateCategories: ['anxietyAndCalming', 'trainingAndBehavior', 'pharmacyAndMedical'] },
  { slug: 'dog-reactivity', title: 'Dog Reactivity Guide', desc: 'Understanding and managing reactive dogs. Covers leash reactivity, triggers, counter-conditioning techniques, management strategies, and professional help.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'anxietyAndCalming'] },
  { slug: 'dog-resource-guarding', title: 'Dog Resource Guarding', desc: 'Understanding and treating resource guarding in dogs. Covers food bowl aggression, toy guarding, trading exercises, and when to seek professional help.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior'] },
  { slug: 'puppy-potty-training', title: 'Puppy Potty Training Guide', desc: 'Complete puppy potty training guide covering schedule, crate training method, bell training, troubleshooting accidents, and timeline expectations.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'foodAndNutrition'] },
  { slug: 'puppy-crate-training', title: 'Puppy Crate Training Guide', desc: 'Step-by-step crate training for puppies. Covers choosing the right crate, building positive associations, nighttime training, and common mistakes.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior'] },
  { slug: 'puppy-biting-solutions', title: 'Puppy Biting and Mouthing Solutions', desc: 'How to stop puppy biting and nipping. Covers bite inhibition, redirecting techniques, appropriate chew toys, and when biting indicates a problem.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'foodAndNutrition'] },
  { slug: 'dog-impulse-control', title: 'Dog Impulse Control Training', desc: 'Teaching impulse control to dogs including leave it, wait, settle, and self-regulation exercises for excitable or reactive dogs.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior'] },
  { slug: 'dog-recall-training', title: 'Dog Recall Training Guide', desc: 'How to train a reliable recall (come when called). Covers foundation training, proofing in distractions, emergency recall, and long-line techniques.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'devicesGpsAndTech'] },
  { slug: 'dog-loose-leash-walking', title: 'Loose Leash Walking Training', desc: 'How to teach your dog to walk without pulling. Covers equipment choices, training techniques, troubleshooting, and making walks enjoyable.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'groomingAndSupplements'] },
  { slug: 'dog-aggression-guide', title: 'Understanding Dog Aggression', desc: 'Types of aggression in dogs including fear, territorial, and redirected aggression. Covers warning signs, management, and working with a behaviorist.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'anxietyAndCalming', 'pharmacyAndMedical'] },
  { slug: 'dog-excessive-barking', title: 'Excessive Barking Solutions', desc: 'Why dogs bark excessively and how to reduce it. Covers demand barking, alert barking, anxiety barking, and positive training methods to address each type.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'anxietyAndCalming'] },
  { slug: 'dog-digging-solutions', title: 'Dog Digging Behavior Solutions', desc: 'Why dogs dig and how to redirect the behavior. Covers boredom digging, escape digging, instinct-driven digging, and creating appropriate dig zones.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior'] },
  { slug: 'dog-socialization-guide', title: 'Dog Socialization Guide', desc: 'Complete socialization guide for puppies and adult dogs. Covers critical periods, socialization checklist, safe exposure techniques, and common mistakes.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'walkingSittingBoarding'] },
  { slug: 'cat-clicker-training', title: 'Cat Clicker Training Guide', desc: 'How to clicker train your cat. Covers getting started, teaching tricks, solving behavior problems, and mental enrichment through training.', animal: 'cats', affiliateCategories: ['trainingAndBehavior', 'foodAndNutrition'] },
  { slug: 'cat-aggression-guide', title: 'Cat Aggression Causes and Solutions', desc: 'Types of aggression in cats including play, fear, redirected, and petting-induced aggression. Covers triggers, prevention, and behavior modification.', animal: 'cats', affiliateCategories: ['anxietyAndCalming', 'teleVetsAndClinics'] },
  { slug: 'introducing-cats', title: 'Introducing Cats to Each Other', desc: 'Step-by-step guide to introducing a new cat to your existing cats. Covers scent swapping, site swapping, visual introduction, and troubleshooting.', animal: 'cats', affiliateCategories: ['anxietyAndCalming', 'foodAndNutrition'] },
  { slug: 'introducing-dogs-cats', title: 'Introducing Dogs and Cats', desc: 'How to safely introduce dogs and cats. Covers preparation, controlled introductions, body language reading, and managing a multi-species household.', animal: 'general', affiliateCategories: ['trainingAndBehavior', 'anxietyAndCalming'] },
  { slug: 'dog-travel-anxiety', title: 'Dog Travel and Car Anxiety', desc: 'Managing travel anxiety in dogs including car sickness, crate stress, and flying anxiety. Covers desensitization, medications, and travel preparation.', animal: 'dogs', affiliateCategories: ['anxietyAndCalming', 'devicesGpsAndTech', 'walkingSittingBoarding'] },
  { slug: 'puppy-teething-guide', title: 'Puppy Teething Guide', desc: 'Complete puppy teething timeline and relief guide. Covers teething symptoms, safe chew toys, frozen treats, and when to worry about dental development.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'groomingAndSupplements'] },
  { slug: 'dog-mental-enrichment', title: 'Dog Mental Enrichment Guide', desc: 'Keeping your dog mentally stimulated through puzzle toys, scent work, food enrichment, training games, and brain exercises to prevent boredom.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'foodAndNutrition'] },
  { slug: 'cat-enrichment-guide', title: 'Indoor Cat Enrichment Guide', desc: 'Keeping indoor cats happy and stimulated. Covers climbing spaces, window perches, puzzle feeders, play routines, and environmental enrichment ideas.', animal: 'cats', affiliateCategories: ['foodAndNutrition', 'devicesGpsAndTech'] },
];

// ============================================================
// CLUSTER 7: Product Buying Guides (28 pages)
// ============================================================
export const productPages = [
  { slug: 'best-dog-collars', title: 'Best Dog Collars', desc: 'Expert guide to choosing the best dog collar by type: flat, martingale, breakaway, and smart collars. Covers sizing, materials, and top picks for every dog.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'devicesGpsAndTech'] },
  { slug: 'best-dog-leashes', title: 'Best Dog Leashes', desc: 'Complete dog leash buying guide covering standard, retractable, hands-free, and training leashes. Includes top picks for every walking style and dog size.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'trainingAndBehavior'] },
  { slug: 'best-dog-food-for-puppies', title: 'Best Puppy Food', desc: 'Top puppy food brands reviewed. Covers large breed vs small breed formulas, wet vs dry, grain-free considerations, and feeding schedule recommendations.', animal: 'dogs', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'best-dog-food-seniors', title: 'Best Dog Food for Senior Dogs', desc: 'Top senior dog food brands reviewed. Covers joint support formulas, low-calorie options, kidney-friendly diets, and transitioning to senior food.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'groomingAndSupplements'] },
  { slug: 'best-cat-food-for-kittens', title: 'Best Kitten Food', desc: 'Top kitten food brands reviewed covering wet food, dry food, and combination feeding. Includes nutritional requirements and feeding schedule by age.', animal: 'cats', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'best-cat-food-seniors', title: 'Best Cat Food for Senior Cats', desc: 'Top senior cat food brands reviewed. Covers kidney support, weight management, hydration, and transitioning older cats to appropriate nutrition.', animal: 'cats', affiliateCategories: ['foodAndNutrition', 'groomingAndSupplements'] },
  { slug: 'best-dog-bowls', title: 'Best Dog Bowls and Feeders', desc: 'Guide to choosing the best dog bowls including slow feeders, elevated bowls, stainless steel, and ceramic options. Covers sizing and safety considerations.', animal: 'dogs', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'best-dog-gates', title: 'Best Dog Gates and Barriers', desc: 'Top dog gates for stairs, doorways, and wide openings. Covers pressure-mounted, hardware-mounted, freestanding, and outdoor gate options.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'devicesGpsAndTech'] },
  { slug: 'best-pet-travel-carriers', title: 'Best Pet Travel Carriers', desc: 'Top airline-approved pet carriers for dogs and cats. Covers soft-sided, hard-sided, wheeled, and backpack carriers with size guides for major airlines.', animal: 'general', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'best-dog-supplements', title: 'Best Dog Supplements', desc: 'Guide to the best dog supplements for joints, skin, digestion, and overall health. Covers glucosamine, fish oil, probiotics, and multivitamins.', animal: 'dogs', affiliateCategories: ['groomingAndSupplements', 'foodAndNutrition'] },
  { slug: 'best-cat-supplements', title: 'Best Cat Supplements', desc: 'Top cat supplements for joint health, hairball control, urinary support, and overall wellness. Includes dosing guidelines and vet-recommended brands.', animal: 'cats', affiliateCategories: ['groomingAndSupplements', 'foodAndNutrition'] },
  { slug: 'best-dog-anxiety-products', title: 'Best Dog Anxiety Products', desc: 'Comprehensive review of dog anxiety products including ThunderShirts, calming treats, pheromone diffusers, weighted blankets, and calming music.', animal: 'dogs', affiliateCategories: ['anxietyAndCalming', 'groomingAndSupplements'] },
  { slug: 'best-cat-anxiety-products', title: 'Best Cat Anxiety Products', desc: 'Top products for reducing cat anxiety and stress. Covers Feliway diffusers, calming treats, hiding spots, and environmental solutions.', animal: 'cats', affiliateCategories: ['anxietyAndCalming'] },
  { slug: 'best-dog-shampoos', title: 'Best Dog Shampoos', desc: 'Top dog shampoos for every coat type and skin condition. Covers medicated, hypoallergenic, deodorizing, and puppy-safe formulas.', animal: 'dogs', affiliateCategories: ['groomingAndSupplements'] },
  { slug: 'best-pet-cameras', title: 'Best Pet Cameras', desc: 'Top pet cameras with treat tossing, two-way audio, and motion detection. Covers Furbo, Petcube, Wyze, and budget-friendly options.', animal: 'general', affiliateCategories: ['devicesGpsAndTech'] },
  { slug: 'best-dog-gps-trackers', title: 'Best Dog GPS Trackers', desc: 'Top GPS trackers for dogs compared. Covers Fi, Whistle, Tractive, AirTag, and Halo with range, battery life, and subscription comparisons.', animal: 'dogs', affiliateCategories: ['devicesGpsAndTech'] },
  { slug: 'best-dog-puzzle-toys', title: 'Best Dog Puzzle Toys', desc: 'Top puzzle toys and interactive feeders for dogs. Covers difficulty levels, food puzzles, snuffle mats, and toys that prevent boredom and anxiety.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'trainingAndBehavior'] },
  { slug: 'best-bird-cages', title: 'Best Bird Cages', desc: 'Guide to choosing the best bird cage by species. Covers cage sizes for parakeets to macaws, bar spacing, materials, and setup accessories.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'best-reptile-terrariums', title: 'Best Reptile Terrariums', desc: 'Top terrariums for bearded dragons, leopard geckos, ball pythons, and other reptiles. Covers sizes, ventilation, heating, and lighting compatibility.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'best-aquarium-filters', title: 'Best Aquarium Filters', desc: 'Top aquarium filters for freshwater and saltwater tanks. Covers HOB, canister, sponge, and internal filters with tank size recommendations.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'best-aquarium-lights', title: 'Best Aquarium Lights', desc: 'Guide to the best aquarium lighting for planted tanks, reef tanks, and freshwater aquariums. Covers LED, spectrum, timing, and plant growth requirements.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'best-reptile-heating', title: 'Best Reptile Heating Equipment', desc: 'Guide to reptile heating solutions including heat lamps, ceramic heaters, under-tank heaters, and radiant heat panels with thermostat recommendations.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'best-dog-beds-2025', title: 'Best Dog Beds 2025', desc: 'Updated guide to the best dog beds including orthopedic, bolster, cooling, and indestructible options for every size and sleeping style.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'groomingAndSupplements'] },
  { slug: 'best-cat-litter-boxes', title: 'Best Cat Litter Boxes', desc: 'Top cat litter boxes reviewed including self-cleaning, covered, top-entry, and jumbo options. Covers multi-cat setups and odor control.', animal: 'cats', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'best-dog-car-seats', title: 'Best Dog Car Seats and Safety Restraints', desc: 'Top dog car seats, harnesses, and barriers for safe travel. Covers crash-tested options, size guides, and state safety requirements.', animal: 'dogs', affiliateCategories: ['devicesGpsAndTech', 'foodAndNutrition'] },
  { slug: 'best-dog-rain-gear', title: 'Best Dog Raincoats and Boots', desc: 'Top waterproof gear for dogs including raincoats, boots, and paw protectors. Covers sizing, materials, and options for every climate.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'groomingAndSupplements'] },
  { slug: 'best-bird-food', title: 'Best Bird Food by Species', desc: 'Top bird food brands for parrots, cockatiels, finches, and canaries. Covers pellets, seed mixes, fresh food, and nutritional requirements by species.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'best-small-animal-cages', title: 'Best Small Animal Cages and Habitats', desc: 'Top cages for rabbits, guinea pigs, hamsters, and ferrets. Covers minimum sizes, bedding options, enrichment, and multi-level setups.', animal: 'general', affiliateCategories: ['birdReptileExotic'] },
];

// ============================================================
// CLUSTER 8: Breed-Specific Health (28 pages)
// ============================================================
export const breedHealthPages = [
  { slug: 'labrador-health-guide', title: 'Labrador Retriever Health Guide', desc: 'Common health problems in Labrador Retrievers including hip dysplasia, obesity, ear infections, and cancer. Covers prevention, screening, and care.', animal: 'dogs', breed: 'labrador-retriever', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'foodAndNutrition', 'dnaAndTesting'] },
  { slug: 'golden-retriever-health-guide', title: 'Golden Retriever Health Guide', desc: 'Health issues common in Golden Retrievers including cancer, hip dysplasia, heart disease, and skin conditions. Covers screenings and preventive care.', animal: 'dogs', breed: 'golden-retriever', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'german-shepherd-health-guide', title: 'German Shepherd Health Guide', desc: 'Common German Shepherd health problems including hip/elbow dysplasia, DM, bloat, and allergies. Covers genetic testing and preventive care.', animal: 'dogs', breed: 'german-shepherd', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'french-bulldog-health-guide', title: 'French Bulldog Health Guide', desc: 'Health challenges common in French Bulldogs including BOAS, spinal issues, skin fold dermatitis, and allergies. Covers surgery options and daily care.', animal: 'dogs', breed: 'french-bulldog', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'poodle-health-guide', title: 'Poodle Health Guide', desc: 'Health issues in Standard, Miniature, and Toy Poodles including Addisons, bloat, hip dysplasia, and eye diseases. Covers genetic testing.', animal: 'dogs', breed: 'poodle', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'bulldog-health-guide', title: 'English Bulldog Health Guide', desc: 'Comprehensive health guide for English Bulldogs covering breathing issues, skin problems, joint disease, and heat sensitivity. Covers daily management.', animal: 'dogs', breed: 'english-bulldog', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'rottweiler-health-guide', title: 'Rottweiler Health Guide', desc: 'Common Rottweiler health issues including cancer, hip dysplasia, heart conditions, and cruciate ligament tears. Covers prevention and screening.', animal: 'dogs', breed: 'rottweiler', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'yorkshire-terrier-health-guide', title: 'Yorkshire Terrier Health Guide', desc: 'Health issues in Yorkies including dental disease, liver shunt, collapsed trachea, and luxating patella. Covers small dog care considerations.', animal: 'dogs', breed: 'yorkshire-terrier', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'dachshund-health-guide', title: 'Dachshund Health Guide', desc: 'Dachshund health problems including IVDD, obesity, dental disease, and joint issues. Covers back injury prevention and weight management.', animal: 'dogs', breed: 'dachshund', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'boxer-health-guide', title: 'Boxer Health Guide', desc: 'Common Boxer health problems including cancer, heart disease (ARVC), hip dysplasia, and thyroid issues. Covers screenings and preventive care.', animal: 'dogs', breed: 'boxer', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'husky-health-guide', title: 'Siberian Husky Health Guide', desc: 'Health issues in Siberian Huskies including eye conditions, hip dysplasia, epilepsy, and zinc deficiency. Covers exercise needs and coat care.', animal: 'dogs', breed: 'siberian-husky', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'chihuahua-health-guide', title: 'Chihuahua Health Guide', desc: 'Common Chihuahua health issues including dental disease, luxating patella, heart murmurs, and hypoglycemia. Covers small breed care considerations.', animal: 'dogs', breed: 'chihuahua', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'shih-tzu-health-guide', title: 'Shih Tzu Health Guide', desc: 'Health problems in Shih Tzus including eye issues, breathing problems, dental disease, and ear infections. Covers grooming needs and preventive care.', animal: 'dogs', breed: 'shih-tzu', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'great-dane-health-guide', title: 'Great Dane Health Guide', desc: 'Health challenges in Great Danes including bloat/GDV, heart disease, hip dysplasia, and Wobbler syndrome. Covers giant breed care and feeding.', animal: 'dogs', breed: 'great-dane', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'cavalier-king-charles-health-guide', title: 'Cavalier King Charles Spaniel Health Guide', desc: 'Health issues in Cavaliers including heart disease (MVD), syringomyelia, eye problems, and hip dysplasia. Covers screening protocols.', animal: 'dogs', breed: 'cavalier-king-charles', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'maine-coon-health-guide', title: 'Maine Coon Health Guide', desc: 'Common health problems in Maine Coon cats including HCM, hip dysplasia, spinal muscular atrophy, and polycystic kidney disease.', animal: 'cats', breed: 'maine-coon', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'persian-health-guide', title: 'Persian Cat Health Guide', desc: 'Health issues in Persian cats including PKD, breathing problems, eye conditions, dental disease, and skin fold infections. Covers grooming needs.', animal: 'cats', breed: 'persian', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'siamese-health-guide', title: 'Siamese Cat Health Guide', desc: 'Common Siamese cat health problems including respiratory issues, amyloidosis, dental disease, and progressive retinal atrophy. Covers breed-specific care.', animal: 'cats', breed: 'siamese', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'bengal-health-guide', title: 'Bengal Cat Health Guide', desc: 'Health concerns in Bengal cats including HCM, PRA, flat-chested kitten syndrome, and anesthetic sensitivity. Covers genetic testing.', animal: 'cats', breed: 'bengal', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'ragdoll-health-guide', title: 'Ragdoll Cat Health Guide', desc: 'Health issues in Ragdoll cats including HCM, bladder stones, and GI sensitivity. Covers genetic testing, nutrition, and preventive care.', animal: 'cats', breed: 'ragdoll', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'british-shorthair-health-guide', title: 'British Shorthair Health Guide', desc: 'Common health problems in British Shorthair cats including HCM, obesity, dental disease, and hemophilia B. Covers weight management.', animal: 'cats', breed: 'british-shorthair', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'scottish-fold-health-guide', title: 'Scottish Fold Health Guide', desc: 'Health issues specific to Scottish Fold cats including osteochondrodysplasia, ear problems, and HCM. Covers the cartilage condition controversy.', animal: 'cats', breed: 'scottish-fold', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical'] },
  { slug: 'sphynx-health-guide', title: 'Sphynx Cat Health Guide', desc: 'Health concerns in Sphynx cats including HCM, skin conditions, temperature sensitivity, and dental disease. Covers hairless cat care requirements.', animal: 'cats', breed: 'sphynx', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'corgi-health-guide', title: 'Corgi Health Guide', desc: 'Common health issues in Pembroke and Cardigan Welsh Corgis including IVDD, hip dysplasia, DM, and obesity. Covers prevention strategies.', animal: 'dogs', breed: 'pembroke-welsh-corgi', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'pit-bull-health-guide', title: 'Pit Bull Health Guide', desc: 'Health issues common in American Pit Bull Terriers including allergies, hip dysplasia, thyroid disease, and heart conditions. Covers preventive care.', animal: 'dogs', breed: 'american-pit-bull-terrier', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'groomingAndSupplements'] },
  { slug: 'beagle-health-guide', title: 'Beagle Health Guide', desc: 'Common Beagle health problems including epilepsy, hypothyroidism, cherry eye, and obesity. Covers weight management and preventive screening.', animal: 'dogs', breed: 'beagle', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'foodAndNutrition'] },
  { slug: 'doberman-health-guide', title: 'Doberman Pinscher Health Guide', desc: 'Health issues in Doberman Pinschers including DCM, Wobbler syndrome, von Willebrand disease, and hypothyroidism. Covers cardiac screening.', animal: 'dogs', breed: 'doberman-pinscher', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
  { slug: 'abyssinian-health-guide', title: 'Abyssinian Cat Health Guide', desc: 'Health concerns in Abyssinian cats including renal amyloidosis, PRA, gingivitis, and patellar luxation. Covers genetic testing and prevention.', animal: 'cats', breed: 'abyssinian', affiliateCategories: ['insuranceAndWellness', 'pharmacyAndMedical', 'dnaAndTesting'] },
];

// ============================================================
// CLUSTER 9: Bird/Fish/Reptile Expansion (52 pages)
// ============================================================
export const exoticPages = [
  // Bird guides (18 pages)
  { slug: 'cockatiel-care-guide', title: 'Cockatiel Complete Care Guide', desc: 'Everything you need to know about cockatiel care including diet, housing, health, training, and common behavior patterns for these popular pet birds.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'budgie-care-guide', title: 'Budgerigar (Budgie) Care Guide', desc: 'Complete guide to budgie care covering diet, cage setup, health issues, training, and why budgies make excellent first birds.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'african-grey-care-guide', title: 'African Grey Parrot Care Guide', desc: 'Comprehensive African Grey parrot care guide covering diet, mental stimulation, talking ability, common health issues, and lifespan expectations.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'conure-care-guide', title: 'Conure Care Guide', desc: 'Complete care guide for Sun Conures, Green Cheek Conures, and other conure species. Covers diet, housing, noise levels, and health care.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'macaw-care-guide', title: 'Macaw Care Guide', desc: 'Comprehensive macaw care covering housing requirements, diet, socialization, health issues, and the commitment of owning a large parrot.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'lovebird-care-guide', title: 'Lovebird Care Guide', desc: 'Complete lovebird care guide covering species differences, housing, diet, social needs, health concerns, and whether lovebirds need a partner.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'finch-care-guide', title: 'Finch and Canary Care Guide', desc: 'Complete care guide for pet finches and canaries. Covers species, diet, cage requirements, breeding, health issues, and singing behavior.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'common-bird-diseases', title: 'Common Pet Bird Diseases', desc: 'Guide to common diseases in pet birds including PBFD, psittacosis, aspergillosis, and avian flu. Covers symptoms, treatment, and prevention.', animal: 'birds', affiliateCategories: ['birdReptileExotic', 'teleVetsAndClinics'] },
  { slug: 'bird-diet-nutrition-guide', title: 'Bird Diet and Nutrition Guide', desc: 'Comprehensive bird nutrition guide covering pellets vs seeds, fresh foods, supplements, and species-specific dietary needs for pet birds.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'bird-enrichment-guide', title: 'Bird Enrichment and Toys Guide', desc: 'Keeping pet birds mentally stimulated through foraging toys, training, socialization, and environmental enrichment to prevent feather plucking.', animal: 'birds', affiliateCategories: ['birdReptileExotic'] },
  // Fish guides (16 pages)
  { slug: 'betta-fish-care-guide', title: 'Betta Fish Complete Care Guide', desc: 'Everything about betta fish care including tank setup, water parameters, feeding, common diseases, tank mates, and debunking betta myths.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'goldfish-care-guide', title: 'Goldfish Complete Care Guide', desc: 'Complete goldfish care guide debunking bowl myths. Covers proper tank size, filtration, diet, varieties, lifespan, and common health issues.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'neon-tetra-care-guide', title: 'Neon Tetra Care Guide', desc: 'Guide to keeping neon tetras including school size, tank setup, water parameters, diet, compatible tank mates, and neon tetra disease.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'guppy-care-guide', title: 'Guppy Care and Breeding Guide', desc: 'Complete guppy care guide covering tank setup, feeding, breeding, fry care, color varieties, and common guppy diseases.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'aquarium-nitrogen-cycle', title: 'Aquarium Nitrogen Cycle Guide', desc: 'Understanding the nitrogen cycle for new aquarium owners. Covers cycling methods, ammonia, nitrite, nitrate, and establishing beneficial bacteria.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'common-fish-diseases', title: 'Common Aquarium Fish Diseases', desc: 'Guide to common fish diseases including ich, fin rot, swim bladder disease, dropsy, and velvet. Covers identification, treatment, and prevention.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'freshwater-vs-saltwater-aquarium', title: 'Freshwater vs Saltwater Aquarium Guide', desc: 'Comparing freshwater and saltwater aquariums in cost, difficulty, maintenance, fish options, and equipment needs for new fishkeepers.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'planted-aquarium-guide', title: 'Planted Aquarium Beginner Guide', desc: 'Getting started with live aquarium plants. Covers easy beginner plants, substrate, lighting, CO2, fertilizers, and creating an aquascape.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'corydoras-care-guide', title: 'Corydoras Catfish Care Guide', desc: 'Complete care guide for Corydoras catfish covering species, tank setup, school size, feeding, breeding, and why they are ideal community fish.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'shrimp-keeping-guide', title: 'Freshwater Shrimp Keeping Guide', desc: 'Guide to keeping freshwater shrimp including Cherry Shrimp, Amano Shrimp, and Crystal Red Shrimp. Covers tank setup, parameters, and breeding.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  // Reptile guides (16 pages)
  { slug: 'bearded-dragon-care-guide', title: 'Bearded Dragon Complete Care Guide', desc: 'Everything about bearded dragon care including enclosure setup, UVB lighting, diet, brumation, common health issues, and handling tips.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'leopard-gecko-care-guide', title: 'Leopard Gecko Complete Care Guide', desc: 'Comprehensive leopard gecko care guide covering enclosure, heating, diet, shedding, common health issues, and morphs.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'ball-python-care-guide', title: 'Ball Python Complete Care Guide', desc: 'Complete ball python care including enclosure setup, humidity, feeding schedules, handling, common health issues, and morph overview.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'corn-snake-care-guide', title: 'Corn Snake Care Guide', desc: 'Beginner-friendly corn snake care guide covering enclosure, temperature, feeding, handling, shedding, and why corn snakes are ideal first snakes.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'crested-gecko-care-guide', title: 'Crested Gecko Care Guide', desc: 'Complete crested gecko care including diet, housing, humidity, handling, health issues, and why they are popular low-maintenance reptile pets.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'blue-tongue-skink-care-guide', title: 'Blue Tongue Skink Care Guide', desc: 'Comprehensive blue tongue skink care covering species, enclosure setup, diet, handling, health issues, and why they make great pet reptiles.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'tortoise-care-guide', title: 'Pet Tortoise Care Guide', desc: 'Complete tortoise care guide covering popular species (Russian, Sulcata, Hermann), enclosure, diet, hibernation, and lifespan considerations.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'chameleon-care-guide', title: 'Chameleon Care Guide', desc: 'Guide to keeping pet chameleons including Veiled and Panther species. Covers enclosure, misting, UVB, diet, and why chameleons need experienced owners.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'common-reptile-diseases', title: 'Common Reptile Diseases and Health Issues', desc: 'Guide to common reptile health problems including MBD, respiratory infections, scale rot, parasites, and shedding issues with treatment guidance.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic', 'teleVetsAndClinics'] },
  { slug: 'reptile-lighting-heating-guide', title: 'Reptile Lighting and Heating Guide', desc: 'Comprehensive guide to reptile lighting and heating including UVB, basking spots, ceramic heaters, thermostats, and species-specific requirements.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'reptile-shedding-guide', title: 'Reptile Shedding Guide', desc: 'Understanding reptile shedding for snakes, lizards, and geckos. Covers normal shedding, stuck shed treatment, humidity management, and warning signs.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic'] },
  { slug: 'turtle-care-guide', title: 'Pet Turtle Care Guide', desc: 'Complete pet turtle care guide covering Red-Eared Sliders, Painted Turtles, and Box Turtles. Includes aquatic and land habitat setup, diet, and health.', animal: 'reptiles', affiliateCategories: ['birdReptileExotic', 'aquariumAndFish'] },
];

// ============================================================
// CLUSTER 10: Location Expansion (28 new cities, expanding from 22 to 50)
// ============================================================
export const newLocationPages = [
  { slug: 'charlotte', city: 'Charlotte', state: 'NC', region: 'Southeast' },
  { slug: 'detroit', city: 'Detroit', state: 'MI', region: 'Midwest' },
  { slug: 'indianapolis', city: 'Indianapolis', state: 'IN', region: 'Midwest' },
  { slug: 'memphis', city: 'Memphis', state: 'TN', region: 'South' },
  { slug: 'baltimore', city: 'Baltimore', state: 'MD', region: 'Mid-Atlantic' },
  { slug: 'milwaukee', city: 'Milwaukee', state: 'WI', region: 'Midwest' },
  { slug: 'albuquerque', city: 'Albuquerque', state: 'NM', region: 'Southwest' },
  { slug: 'tucson', city: 'Tucson', state: 'AZ', region: 'Southwest' },
  { slug: 'sacramento', city: 'Sacramento', state: 'CA', region: 'West Coast' },
  { slug: 'kansas-city', city: 'Kansas City', state: 'MO', region: 'Midwest' },
  { slug: 'mesa', city: 'Mesa', state: 'AZ', region: 'Southwest' },
  { slug: 'omaha', city: 'Omaha', state: 'NE', region: 'Midwest' },
  { slug: 'raleigh', city: 'Raleigh', state: 'NC', region: 'Southeast' },
  { slug: 'minneapolis', city: 'Minneapolis', state: 'MN', region: 'Midwest' },
  { slug: 'tampa', city: 'Tampa', state: 'FL', region: 'Southeast' },
  { slug: 'new-orleans', city: 'New Orleans', state: 'LA', region: 'South' },
  { slug: 'cleveland', city: 'Cleveland', state: 'OH', region: 'Midwest' },
  { slug: 'pittsburgh', city: 'Pittsburgh', state: 'PA', region: 'Mid-Atlantic' },
  { slug: 'orlando', city: 'Orlando', state: 'FL', region: 'Southeast' },
  { slug: 'st-louis', city: 'St. Louis', state: 'MO', region: 'Midwest' },
  { slug: 'richmond', city: 'Richmond', state: 'VA', region: 'Mid-Atlantic' },
  { slug: 'salt-lake-city', city: 'Salt Lake City', state: 'UT', region: 'West' },
  { slug: 'honolulu', city: 'Honolulu', state: 'HI', region: 'Pacific' },
  { slug: 'oklahoma-city', city: 'Oklahoma City', state: 'OK', region: 'South' },
  { slug: 'louisville', city: 'Louisville', state: 'KY', region: 'South' },
  { slug: 'birmingham', city: 'Birmingham', state: 'AL', region: 'South' },
  { slug: 'buffalo', city: 'Buffalo', state: 'NY', region: 'Northeast' },
  { slug: 'cincinnati', city: 'Cincinnati', state: 'OH', region: 'Midwest' },
];

// ============================================================
// CLUSTER 11: Comparison + Life-Stage (20 pages)
// ============================================================
export const comparisonPages = [
  { slug: 'compare-fresh-cat-food', title: 'Best Fresh Cat Food Delivery Services Compared', desc: 'Comparing Smalls, Nom Nom, and other fresh cat food delivery services. Covers ingredients, pricing, meal plans, and which is best for your cat.', animal: 'cats', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'compare-rabbit-insurance', title: 'Best Rabbit and Exotic Pet Insurance Compared', desc: 'Comparing exotic pet insurance options for rabbits, birds, reptiles, and small animals. Covers coverage, pricing, and what to look for.', animal: 'general', affiliateCategories: ['insuranceAndWellness'] },
  { slug: 'compare-bird-supplies', title: 'Best Bird Supply Stores Compared', desc: 'Comparing online bird supply stores for cages, food, toys, and accessories. Covers Chewy, PetSmart, specialty stores, and pricing.', animal: 'birds', affiliateCategories: ['birdReptileExotic', 'foodAndNutrition'] },
  { slug: 'compare-aquarium-equipment', title: 'Best Aquarium Equipment Stores Compared', desc: 'Comparing aquarium equipment retailers for filters, lights, and supplies. Covers Aquarium Co-Op, Marine Depot, and big-box pet stores.', animal: 'fish', affiliateCategories: ['aquariumAndFish'] },
  { slug: 'compare-cat-gps-tracker', title: 'Best Cat GPS Trackers Compared', desc: 'Comparing GPS trackers designed for cats including Tractive, Tabcat, and other lightweight options. Covers range, battery life, and cat-specific features.', animal: 'cats', affiliateCategories: ['devicesGpsAndTech'] },
  { slug: 'compare-dog-food-subscription', title: 'Best Dog Food Subscription Services Compared', desc: "Comparing dog food subscription services including Farmer's Dog, Ollie, PetPlate, and Nom Nom. Covers pricing, ingredients, and convenience.", animal: 'dogs', affiliateCategories: ['foodAndNutrition'] },
  { slug: 'compare-pet-pharmacy', title: 'Best Online Pet Pharmacies Compared', desc: 'Comparing online pet pharmacies for prescription and OTC medications. Covers 1-800-PetMeds, Chewy Pharmacy, PetCareRx, and pricing.', animal: 'general', affiliateCategories: ['pharmacyAndMedical'] },
  { slug: 'compare-dog-dna-test', title: 'Best Dog DNA Tests Compared', desc: 'Embark vs Wisdom Panel vs Orivet dog DNA tests compared. Covers breed detection accuracy, health screening, pricing, and which test is best.', animal: 'dogs', affiliateCategories: ['dnaAndTesting'] },
  { slug: 'dog-breeding-guide', title: 'Responsible Dog Breeding Guide', desc: 'Comprehensive guide to responsible dog breeding covering health testing, genetics, whelping preparation, puppy care, and ethical breeding standards.', animal: 'dogs', affiliateCategories: ['dnaAndTesting', 'insuranceAndWellness', 'foodAndNutrition'] },
  { slug: 'dog-pregnancy-guide', title: 'Dog Pregnancy and Whelping Guide', desc: 'Complete guide to dog pregnancy from mating through whelping. Covers signs of pregnancy, nutrition, preparing a whelping box, labor stages, and newborn care.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'teleVetsAndClinics', 'insuranceAndWellness'] },
  { slug: 'cat-pregnancy-guide', title: 'Cat Pregnancy and Queening Guide', desc: 'Guide to cat pregnancy covering signs, nutrition, preparing for kittens, labor stages, and neonatal kitten care for the first weeks of life.', animal: 'cats', affiliateCategories: ['foodAndNutrition', 'teleVetsAndClinics'] },
  { slug: 'adolescent-dog-guide', title: 'Adolescent Dog Behavior Guide', desc: 'Understanding the teenage dog phase (6-18 months). Covers regression in training, hormonal changes, exercise needs, and surviving canine adolescence.', animal: 'dogs', affiliateCategories: ['trainingAndBehavior', 'anxietyAndCalming'] },
  { slug: 'geriatric-dog-care', title: 'Geriatric Dog Care Guide', desc: 'Caring for senior dogs in their final years. Covers cognitive decline, mobility support, comfort care, end-of-life decisions, and quality of life assessment.', animal: 'dogs', affiliateCategories: ['pharmacyAndMedical', 'groomingAndSupplements', 'insuranceAndWellness'] },
  { slug: 'geriatric-cat-care', title: 'Geriatric Cat Care Guide', desc: 'Caring for senior cats including common age-related conditions, comfort modifications, nutritional needs, and quality of life considerations.', animal: 'cats', affiliateCategories: ['pharmacyAndMedical', 'foodAndNutrition', 'insuranceAndWellness'] },
  { slug: 'pet-loss-grief-guide', title: 'Pet Loss and Grief Support Guide', desc: 'Coping with the loss of a pet. Covers the grief process, memorial options, helping children understand pet loss, and when to consider a new pet.', animal: 'general', affiliateCategories: [] },
  { slug: 'new-puppy-checklist', title: 'New Puppy Checklist and First Month Guide', desc: 'Everything you need for a new puppy including supplies checklist, first vet visit, potty training start, socialization window, and feeding schedule.', animal: 'dogs', affiliateCategories: ['foodAndNutrition', 'trainingAndBehavior', 'insuranceAndWellness', 'groomingAndSupplements'] },
  { slug: 'new-kitten-checklist', title: 'New Kitten Checklist and First Month Guide', desc: 'Complete checklist for bringing home a new kitten. Covers supplies, kitten-proofing, first vet visit, feeding schedule, and litter training basics.', animal: 'cats', affiliateCategories: ['foodAndNutrition', 'insuranceAndWellness'] },
  { slug: 'compare-calming-products', title: 'Best Pet Calming Products Compared', desc: 'Comparing calming products for anxious pets: ThunderShirt vs Adaptil vs CBD treats vs prescription medications. Covers effectiveness and best use cases.', animal: 'general', affiliateCategories: ['anxietyAndCalming', 'pharmacyAndMedical'] },
  { slug: 'compare-pet-boarding', title: 'Best Pet Boarding Services Compared', desc: 'Comparing Rover, Wag!, Camp Bow Wow, and traditional boarding facilities. Covers pricing, services, safety, and which is best for your pet.', animal: 'general', affiliateCategories: ['walkingSittingBoarding'] },
  { slug: 'multi-pet-household-guide', title: 'Multi-Pet Household Guide', desc: 'Managing a household with multiple pets. Covers introducing new pets, resource management, feeding strategies, and maintaining harmony.', animal: 'general', affiliateCategories: ['foodAndNutrition', 'anxietyAndCalming'] },
];
